name: .NET

on:
  push:
    branches: [ "master" ]
    paths:
      - dotnet/**
  pull_request:
    branches: [ "master" ]
    paths:
      - dotnet/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore dotnet/TeamCityClient.slnx
    - name: Build
      run: dotnet build dotnet/TeamCityClient.slnx --no-restore
    - name: Test
      run: dotnet test dotnet/TeamCityClient.slnx --no-build --verbosity normal
